alias dcc='drush cc all'
alias guard='bundle exec guard'
alias gpulst='git pull origin staging'
alias gpusst='git push origin staging'
alias gpusm='git push origin master'
alias gpulm='git pull origin master'
alias gstat='git status'
alias dfle='drush fl --status=enabled'
alias dfl='drush fl'
alias dfd='drush fd'
alias sqlc='drush sqlc'
alias fixperm='sudo find -type f -exec chmod 664 {} \;;sudo find -type d -exec chmod 775 {} \;;sudo chown -R vagrant *;'
alias offagg='drush vset preprocess_js 0 --yes && drush vset preprocess_css 0 --yes'
alias vi='vim'
alias sys-update='sudo unattended-upgrade'
